# Generated by Django 5.2.17 on 2026-08-08 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('template_code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], db_index=True, default='QUEUED', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('source_event_id', models.UUIDField(db_index=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_notification',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_event_id', 'channel', 'user_id'), name='notification_uniq_per_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_preference',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'category', 'channel'), name='notification_uniq_pref')],
            },
        ),
    ]
