# Generated by Django 5.1.15 on 2026-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('from_id', models.BigIntegerField()),
                ('to_id', models.BigIntegerField()),
                ('rows_checked', models.BigIntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('broken_at_id', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_chain_verification',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.CharField(db_index=True, max_length=50)),
                ('actor_type', models.CharField(blank=True, max_length=30)),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(db_index=True, max_length=50)),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.BigIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('causation_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['id'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='audit_aggregate_idx'), models.Index(fields=['-occurred_at'], name='audit_occurred_idx')],
            },
        ),
    ]
