# Generated by Django 5.2.17 on 2026-08-08 04:35

import django.db.models.deletion
import platform_common.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('source_type', models.CharField(choices=[('EXTERNAL_BANK', 'External bank account'), ('DEBIT_CARD', 'Debit card'), ('WALLET', 'Wallet')], max_length=20)),
                ('display_name', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_funding_source',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('key', models.CharField(max_length=120)),
                ('endpoint', models.CharField(max_length=80)),
                ('request_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=12)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_idempotency',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'key', 'endpoint'), name='payments_uniq_idem_record')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('txn_type', models.CharField(choices=[('FUNDING', 'Funding'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('rail', models.CharField(choices=[('INTERNAL', 'Internal (same bank)'), ('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International'), ('BANK_DEBIT', 'External bank debit'), ('CARD', 'Debit card'), ('WALLET', 'Wallet')], max_length=20)),
                ('direction', models.CharField(max_length=6)),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('dest_amount', platform_common.db.fields.MoneyField(blank=True, null=True)),
                ('dest_currency', models.CharField(blank=True, max_length=3)),
                ('beneficiary_id', models.UUIDField(blank=True, null=True)),
                ('beneficiary_masked', models.CharField(blank=True, max_length=40)),
                ('funding_source_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('VALIDATED', 'Validated'), ('RESERVED', 'Funds reserved'), ('SCREENING', 'Screening'), ('APPROVED', 'Approved'), ('UNDER_REVIEW', 'Under review'), ('POSTED', 'Posted to ledger'), ('DISPATCHED', 'Dispatched to rail'), ('SETTLED', 'Settled'), ('RETURNED', 'Returned by rail'), ('REVERSED', 'Reversed'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('COMPENSATION_PENDING', 'Compensation pending')], db_index=True, default='INITIATED', max_length=24)),
                ('status_reason', models.CharField(blank=True, max_length=120)),
                ('hold_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('fraud_decision_id', models.UUIDField(blank=True, null=True)),
                ('fraud_case_id', models.UUIDField(blank=True, null=True)),
                ('fraud_score', models.IntegerField(blank=True, null=True)),
                ('limit_reservation_id', models.CharField(blank=True, max_length=64)),
                ('rail_ref', models.CharField(blank=True, max_length=60)),
                ('schedule_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('purpose_code', models.CharField(blank=True, max_length=40)),
                ('remarks', models.CharField(blank=True, max_length=140)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', '-created_at'], name='payments_acct_hist_idx'), models.Index(fields=['status', 'created_at'], name='payments_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'idempotency_key'), name='payments_uniq_idem_per_user')],
            },
        ),
        migrations.CreateModel(
            name='TransferSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField()),
                ('beneficiary_id', models.UUIDField()),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('rail', models.CharField(choices=[('INTERNAL', 'Internal (same bank)'), ('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International'), ('BANK_DEBIT', 'External bank debit'), ('CARD', 'Debit card'), ('WALLET', 'Wallet')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=140)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('runs_completed', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='ACTIVE', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_transfer_schedule',
                'indexes': [models.Index(fields=['status', 'next_run_at'], name='payments_sched_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('COMPENSATED', 'Compensated'), ('COMPENSATION_FAILED', 'Compensation failed')], default='PENDING', max_length=22)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('request', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='payments.transaction')),
            ],
            options={
                'db_table': 'payments_saga_step',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['transaction', 'name'], name='payments_step_idx')],
            },
        ),
    ]
