# Generated by Django 5.2.17 on 2026-08-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty_account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty_masked',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirror_of', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_ref',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
