# Generated by Django 5.2.17 on 2026-08-08 04:26

import django.db.models.deletion
import platform_common.db.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('account_ref', models.UUIDField(primary_key=True, serialize=False)),
                ('txn_count', models.BigIntegerField(default=0)),
                ('mean_amount', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('m2', models.FloatField(default=0.0)),
                ('max_amount', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('last_country', models.CharField(blank=True, max_length=2)),
                ('last_device_hash', models.CharField(blank=True, max_length=80)),
                ('last_txn_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('account_opened_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_account_profile',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_below', models.IntegerField(default=40)),
                ('block_at_or_above', models.IntegerField(default=75)),
                ('safe_harbour_amount', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_threshold',
            },
        ),
        migrations.CreateModel(
            name='FraudDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_ref', models.UUIDField(db_index=True)),
                ('account_ref', models.UUIDField(db_index=True)),
                ('user_ref', models.UUIDField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('REVIEW', 'Review'), ('BLOCK', 'Block')], db_index=True, max_length=10)),
                ('score', models.IntegerField()),
                ('reason_codes', models.JSONField(default=list)),
                ('shadow_codes', models.JSONField(default=list)),
                ('features', models.JSONField(default=dict)),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('rail', models.CharField(max_length=20)),
                ('ruleset_version', models.CharField(blank=True, max_length=40)),
                ('latency_ms', models.IntegerField()),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'fraud_decision',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('txn_ref',), name='fraud_uniq_decision_per_txn')],
            },
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_ref', models.UUIDField(db_index=True)),
                ('account_ref', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=12)),
                ('priority', models.CharField(db_index=True, default='MEDIUM', max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('CONFIRMED_FRAUD', 'Confirmed fraud'), ('FALSE_POSITIVE', 'False positive'), ('INCONCLUSIVE', 'Inconclusive')], max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=64)),
                ('sla_due_at', models.DateTimeField(db_index=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='fraud.frauddecision')),
            ],
            options={
                'db_table': 'fraud_case',
                'ordering': ['sla_due_at'],
            },
        ),
        migrations.CreateModel(
            name='KnownBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ref', models.UUIDField(db_index=True)),
                ('fingerprint', models.CharField(max_length=80)),
                ('first_seen', models.DateTimeField()),
                ('txn_count', models.IntegerField(default=0)),
                ('total_amount', platform_common.db.fields.MoneyField(default=Decimal('0'))),
            ],
            options={
                'db_table': 'fraud_known_beneficiary',
                'constraints': [models.UniqueConstraint(fields=('account_ref', 'fingerprint'), name='fraud_uniq_known_benef')],
            },
        ),
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_type', models.CharField(choices=[('BLACKLIST_BENEFICIARY', 'Blacklisted beneficiary'), ('HIGH_RISK_COUNTRY', 'High-risk country'), ('BLOCKED_DEVICE', 'Blocked device')], db_index=True, max_length=30)),
                ('value', models.CharField(db_index=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('added_by', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_list_entry',
                'constraints': [models.UniqueConstraint(fields=('list_type', 'value'), name='fraud_uniq_list_value')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('condition', models.JSONField()),
                ('weight', models.IntegerField(default=0)),
                ('hard_block', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('ACTIVE', 'Active'), ('SHADOW', 'Shadow'), ('DISABLED', 'Disabled')], default='SHADOW', max_length=10)),
                ('reason_code', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('AMOUNT', 'Amount'), ('VELOCITY', 'Velocity'), ('BENEFICIARY', 'Beneficiary'), ('GEO', 'Geography'), ('DEVICE', 'Device'), ('LIST', 'List match'), ('BEHAVIOUR', 'Behaviour')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_rule',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['mode'], name='fraud_rule_mode_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_count', models.BigIntegerField(default=0)),
                ('shadow_fired_count', models.BigIntegerField(default=0)),
                ('confirmed_fraud', models.BigIntegerField(default=0)),
                ('false_positive', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='fraud.rule')),
            ],
            options={
                'db_table': 'fraud_rule_stat',
            },
        ),
        migrations.CreateModel(
            name='ScreenedTxn',
            fields=[
                ('txn_ref', models.UUIDField(primary_key=True, serialize=False)),
                ('account_ref', models.UUIDField()),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('rail', models.CharField(max_length=20)),
                ('benef_fingerprint', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device_hash', models.CharField(blank=True, max_length=80)),
                ('decision', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'fraud_screened_txn',
                'indexes': [models.Index(fields=['account_ref', '-created_at'], name='fraud_velocity_idx')],
            },
        ),
    ]
