# Generated by Django 5.2.17 on 2026-08-08 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('last_ip_country', models.CharField(blank=True, max_length=2)),
                ('trusted', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_device',
            },
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=40, unique=True)),
                ('public_pem', models.TextField()),
                ('private_pem', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_signing_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('FRAUD_ANALYST', 'Fraud analyst'), ('OPS', 'Operations'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='PENDING', max_length=10)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_user',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.device')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='identity.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.user')),
            ],
            options={
                'db_table': 'identity_refresh_token',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='identity.user'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint_hash'), name='identity_uniq_device'),
        ),
    ]
