# Generated by Django 5.2.17 on 2026-08-10 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ROLE_CHANGE', 'Change role'), ('CREATE_STAFF', 'Create staff user'), ('UNLOCK', 'Unlock account'), ('ACTIVATE', 'Reactivate account'), ('CLOSE', 'Close account'), ('PASSWORD_RESET', 'Force password reset')], max_length=20)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('requested_by', models.UUIDField(db_index=True)),
                ('requested_by_email', models.EmailField(blank=True, max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting a second administrator'), ('APPLIED', 'Approved and applied'), ('REJECTED', 'Rejected'), ('FAILED', 'Approved but could not be applied'), ('WITHDRAWN', 'Withdrawn by the requester')], db_index=True, default='PENDING', max_length=10)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_by_email', models.EmailField(blank=True, max_length=254)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='identity.user')),
            ],
            options={
                'db_table': 'identity_admin_change_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='identity_acr_queue_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('target_user', 'action'), name='identity_uniq_open_change_request')],
            },
        ),
    ]
