# Generated by Django 5.2.17 on 2026-08-08 04:41

import platform_common.db.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_number', models.CharField(max_length=24, unique=True)),
                ('ifsc', models.CharField(blank=True, max_length=16)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('account_type', models.CharField(default='SAVINGS', max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('tier', models.CharField(default='STANDARD', max_length=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('cached_balance', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('balance_as_of', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_account',
            },
        ),
        migrations.CreateModel(
            name='LimitReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField(db_index=True)),
                ('rail', models.CharField(max_length=20)),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('day_window', models.CharField(max_length=20)),
                ('month_window', models.CharField(max_length=20)),
                ('released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_limit_reservation',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('nickname', models.CharField(max_length=60)),
                ('beneficiary_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], max_length=15)),
                ('account_number', models.CharField(max_length=40)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('swift_bic', models.CharField(blank=True, max_length=11)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('cooling_off_until', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_beneficiary',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'fingerprint'), name='account_uniq_beneficiary')],
            },
        ),
        migrations.CreateModel(
            name='LimitPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(default='TIER', max_length=10)),
                ('scope_ref', models.CharField(db_index=True, max_length=64)),
                ('rail', models.CharField(default='ANY', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('per_txn_max', platform_common.db.fields.MoneyField()),
                ('daily_max', platform_common.db.fields.MoneyField()),
                ('monthly_max', platform_common.db.fields.MoneyField()),
                ('daily_count_max', models.PositiveIntegerField(default=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_limit_policy',
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_ref', 'rail'), name='account_uniq_limit_policy')],
            },
        ),
        migrations.CreateModel(
            name='LimitUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField(db_index=True)),
                ('window', models.CharField(max_length=20)),
                ('rail', models.CharField(max_length=20)),
                ('amount_used', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('count_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'account_limit_usage',
                'constraints': [models.UniqueConstraint(fields=('account_id', 'window', 'rail'), name='account_uniq_limit_usage')],
            },
        ),
    ]
