# Generated by Django 5.2.17 on 2026-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='account_uniq_idempotency_key'),
        ),
    ]
