# Generated by Django 5.2.17 on 2026-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='internal_account_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='internal_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
