# Generated by Django 5.2.17 on 2026-08-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_beneficiary_internal_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='cooling_off_until',
        ),
    ]
