# Generated by Django 5.2.17 on 2026-08-08 04:17

import django.db.models.deletion
import platform_common.db.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('account_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('CUSTOMER', 'Customer'), ('CLEARING', 'Clearing'), ('SUSPENSE', 'Suspense'), ('NOSTRO', 'Nostro'), ('FEE', 'Fee income'), ('FX_POSITION', 'FX position')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_account',
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('txn_ref', models.UUIDField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CAPTURED', 'Captured'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ledger_hold',
            },
        ),
        migrations.CreateModel(
            name='InvariantCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('check_name', models.CharField(max_length=60)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('ok', models.BooleanField()),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ledger_invariant_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('entry_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('FUNDING', 'Funding'), ('FEE', 'Fee'), ('FX', 'FX'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('txn_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('narrative', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_journal_entry',
                'ordering': ['-posted_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', platform_common.db.fields.MoneyField()),
                ('currency', models.CharField(max_length=3)),
                ('balance_after', platform_common.db.fields.MoneyField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_posting',
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('ledger_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='balance', serialize=False, to='ledger.ledgeraccount')),
                ('ledger_balance', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('held', platform_common.db.fields.MoneyField(default=Decimal('0'))),
                ('version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_balance',
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_ref__isnull', False)), fields=('account_ref', 'currency'), name='ledger_uniq_customer_account_currency'),
        ),
        migrations.AddField(
            model_name='hold',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='ledger.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='hold',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captured_holds', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='posting',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='posting',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='ledger.ledgeraccount'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(condition=models.Q(('held__gte', Decimal('0'))), name='ledger_held_non_negative'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['status', 'expires_at'], name='ledger_hold_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='ledger_hold_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['ledger_account', '-created_at'], name='ledger_posting_acct_idx'),
        ),
        migrations.AddConstraint(
            model_name='posting',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='ledger_posting_amount_positive'),
        ),
    ]
