# Generated by Django 5.1.15 on 2026-08-08 03:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.BigIntegerField(default=0)),
                ('producer', models.CharField(max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('envelope', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RECEIVED', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pc_inbox_event',
                'indexes': [models.Index(fields=['status', 'received_at'], name='pc_inbox_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('subscriber', models.CharField(max_length=50)),
                ('envelope', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DEAD', 'Dead')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pc_outbox_event',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='pc_outbox_due_idx'), models.Index(fields=['created_at'], name='pc_outbox_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id', 'subscriber'), name='pc_outbox_uniq_event_subscriber')],
            },
        ),
        migrations.CreateModel(
            name='ProjectionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('last_sequence', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pc_projection_cursor',
                'constraints': [models.UniqueConstraint(fields=('projection', 'aggregate_id'), name='pc_cursor_uniq')],
            },
        ),
    ]
