# Generated by Django 5.2.17 on 2026-08-08 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual review')], db_index=True, default='PENDING', max_length=15)),
                ('identity_score', models.IntegerField(blank=True, null=True)),
                ('document_score', models.IntegerField(blank=True, null=True)),
                ('sanctions_hit', models.BooleanField(default=False)),
                ('pep_hit', models.BooleanField(default=False)),
                ('risk_rating', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('provider_ref', models.CharField(blank=True, max_length=60)),
                ('failure_reason', models.CharField(blank=True, max_length=120)),
                ('processing_ms', models.IntegerField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kyc_case',
                'constraints': [models.UniqueConstraint(fields=('application_id',), name='kyc_uniq_per_application')],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('UTILITY_BILL', 'Utility bill'), ('SELFIE', 'Selfie')], max_length=15)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('authenticity_score', models.IntegerField(blank=True, null=True)),
                ('ocr_result', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kyccase')),
            ],
            options={
                'db_table': 'kyc_document',
            },
        ),
        migrations.CreateModel(
            name='KycIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=64)),
                ('national_id_hash', models.CharField(db_index=True, max_length=64)),
                ('nationality', models.CharField(max_length=2)),
                ('address', models.JSONField(default=dict)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='kyc.kyccase')),
            ],
            options={
                'db_table': 'kyc_identity',
            },
        ),
        migrations.CreateModel(
            name='ScreeningHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=30)),
                ('matched_name', models.CharField(max_length=140)),
                ('match_score', models.IntegerField()),
                ('is_pep', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='kyc.kyccase')),
            ],
            options={
                'db_table': 'kyc_screening_hit',
            },
        ),
    ]
