# Generated by Django 5.2.17 on 2026-08-08 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('KYC_PENDING', 'KYC pending'), ('KYC_PASSED', 'KYC passed'), ('KYC_FAILED', 'KYC failed'), ('ELIGIBLE', 'Eligible'), ('MANUAL_REVIEW', 'Manual review'), ('REJECTED', 'Rejected'), ('ACCOUNT_OPENED', 'Account opened'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=16)),
                ('status_reason', models.CharField(blank=True, max_length=120)),
                ('customer_info', models.JSONField(default=dict)),
                ('kyc_case_id', models.UUIDField(blank=True, null=True)),
                ('account_id', models.UUIDField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=24)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=8)),
                ('risk_score', models.IntegerField()),
                ('tier', models.CharField(max_length=12)),
                ('factors', models.JSONField(default=list)),
                ('policy_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='onboarding.application')),
            ],
            options={
                'db_table': 'onboarding_eligibility_result',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='onboarding.application')),
            ],
            options={
                'db_table': 'onboarding_status_history',
                'ordering': ['at'],
            },
        ),
    ]
