# Generated by Django 5.2.17 on 2026-08-08 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=40)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('result', models.JSONField(default=dict)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ops_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailureCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_type', models.CharField(db_index=True, max_length=40)),
                ('source_service', models.CharField(max_length=30)),
                ('subject_ref', models.CharField(db_index=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RETRIED', 'Retried'), ('RESOLVED', 'Resolved'), ('WONT_FIX', "Won't fix")], db_index=True, default='OPEN', max_length=15)),
                ('detail', models.JSONField(default=dict)),
                ('assigned_to', models.CharField(blank=True, max_length=64)),
                ('resolution_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ops_failure_case',
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(fields=('failure_type', 'subject_ref'), name='ops_uniq_failure_case')],
            },
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=30)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reachable', models.BooleanField(default=False)),
                ('queue_depth', models.IntegerField(blank=True, null=True)),
                ('failed_tasks_24h', models.IntegerField(blank=True, null=True)),
                ('outbox_pending', models.IntegerField(blank=True, null=True)),
                ('outbox_dead', models.IntegerField(blank=True, null=True)),
                ('inbox_failed', models.IntegerField(blank=True, null=True)),
                ('oldest_pending_age_s', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'ops_health_snapshot',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['service', '-captured_at'], name='ops_health_latest_idx')],
            },
        ),
    ]
